### ISSUE TITLE
[BUG] Deployed daemon is always unable to send report due to error while fetching partitions with FileNotFoundError

### ISSUE THREAD

**Issue by Pyxsys** [Pyxsys/ttg-healthcheck#214]
### **Describe the bug**
The daemon when deployed on a pi x64 environment, it always fails while fetching disk partition information.
It fails with error:
`FileNotFoundError: [Errno 2] No such file or directory: '/dev/root'`

### **To Reproduce**
1. Deploy the daemon on a PiOS x64 environment
1. Start the daemon using `celebid -s`
2. Wait 30s
3. Open the daemon log

Or

1. Deploy the daemon on a PiOS x64 environment
2. Run the tests via `python3 -m unittest -v`
3. See that the following tests fail:
  - testFetchingPartition 
  - testAddingDiskUsageInfo 

### **Expected behavior**
The tests pass and the daemon is capable of fetching the partition information.

### **Device (please complete the following information):**
 - type: Raspberry Pi
 - model: Raspberry Pi 3 Model B Plus Rev 1.3
 - OS: Debian GNU/Linux 11 (bullseye)
 - version: 11

### **Additional context**
Error as it appears in the failed tests:
```txt
======================================================================
ERROR: testAddingDiskUsageInfo (test.test_report_module.TestSystemReportClass)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/ttg-healthcheck/daemon/test/test_report_module.py", line 99, in testAddingDiskUsageInfo
    self.test_report.add_disk_usage_info()
  File "../daemon/src/system_report.py", line 148, in add_disk_usage_info
    disk_usage['partitions'] = SysScrubber.fetch_disk_partition_status()
  File "../daemon/src/system_report.py", line 476, in fetch_disk_partition_status
    disk_buffer = psutil.disk_usage(partition_path.device)
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 1995, in disk_usage
    return _psplatform.disk_usage(path)
  File "/usr/lib/python3/dist-packages/psutil/_psposix.py", line 169, in disk_usage
    st = os.statvfs(path)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/root'
```
```txt
======================================================================
ERROR: testAddingDiskUsageInfo (test.test_report_module.TestSystemReportClass)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/ttg-healthcheck/daemon/test/test_report_module.py", line 99, in testAddingDiskUsageInfo
    self.test_report.add_disk_usage_info()
  File "../daemon/src/system_report.py", line 148, in add_disk_usage_info
    disk_usage['partitions'] = SysScrubber.fetch_disk_partition_status()
  File "../daemon/src/system_report.py", line 476, in fetch_disk_partition_status
    disk_buffer = psutil.disk_usage(partition_path.device)
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 1995, in disk_usage
    return _psplatform.disk_usage(path)
  File "/usr/lib/python3/dist-packages/psutil/_psposix.py", line 169, in disk_usage
    st = os.statvfs(path)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/root'
```

**Comment by Pyxsys** [comment]
This is known psutil issue.
https://github.com/giampaolo/psutil/issues/1999
https://github.com/DataDog/datadog-agent/pull/10544

Need to update required psutil version to 5.9.0
