### ISSUE TITLE
[BUG] Deployed daemon is always unable to send report due to error while fetching device uuid with IndexError

### ISSUE THREAD

**Issue by Pyxsys** [Pyxsys/ttg-healthcheck#215]
### **Describe the bug**
The daemon fails when deployed on a pi device while fetching the device's uuid. This blocks the flow early and then prevents the rest of the metrics from being retrieved. Theeuuid is a mandatory part of the report, thus it must be added.

### **To Reproduce**
1. Deploy the daemon on a PiOS x64 environment
1. Start the daemon using `celebid -s`
2. Wait 30s
3. Open the daemon log

Or

1. Deploy the daemon on a PiOS x64 environment
2. Run the tests via `python3 -m unittest -v`
3. See that the following tests fail:
  - testRunnerGeneratingReport 
  - testRunnerGeneratingStartupReport

### **Expected behavior**
The tests pass and the daemon is capable of fetching the devices uuid information.

### **Device (please complete the following information):**
 - type: Raspberry Pi
 - model: Raspberry Pi 3 Model B Plus Rev 1.3
 - OS: Debian GNU/Linux 11 (bullseye)
 - version: 11

### **Additional context**
Error as it appears in the failed tests:
```txt
======================================================================
ERROR: testRunnerGeneratingReport (test.test_report_requests.TestRunner)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.9/unittest/mock.py", line 1337, in patched
    return func(*newargs, **newkeywargs)
  File "/home/pi/ttg-healthcheck/daemon/test/test_report_requests.py", line 35, in testRunnerGeneratingReport
    self.test_runner.gen_report()
  File "../daemon/src/system_report.py", line 32, in gen_report
    self.init_report()
  File "../daemon/src/system_report.py", line 27, in init_report
    self.report.add_device_uuid()
  File "../daemon/src/system_report.py", line 124, in add_device_uuid
    uuid=SysScrubber.fetch_device_uuid()
  File "../daemon/src/system_report.py", line 209, in fetch_device_uuid
    uuid=re.findall(pattern, extract.read(), flags)[0]
IndexError: list index out of range
```
```txt
======================================================================
ERROR: testRunnerGeneratingStartupReport (test.test_report_requests.TestRunner)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.9/unittest/mock.py", line 1337, in patched
    return func(*newargs, **newkeywargs)
  File "/home/pi/ttg-healthcheck/daemon/test/test_report_requests.py", line 49, in testRunnerGeneratingStartupReport
    self.test_runner.gen_startup_report()
  File "../daemon/src/system_report.py", line 40, in gen_startup_report
    self.init_report()
  File "../daemon/src/system_report.py", line 27, in init_report
    self.report.add_device_uuid()
  File "../daemon/src/system_report.py", line 124, in add_device_uuid
    uuid=SysScrubber.fetch_device_uuid()
  File "../daemon/src/system_report.py", line 209, in fetch_device_uuid
    uuid=re.findall(pattern, extract.read(), flags)[0]
IndexError: list index out of range
```

Error as it appears in the log:
```txt
Starting new report routine at 2022-03-06 16:44:56.555766
        Writing report...
Traceback (most recent call last):
  File "/home/pi/ttg-healthcheck/daemon/src/system_report.py", line 608, in <module>
    main(sys.argv[1], sys.argv[2])
  File "/home/pi/ttg-healthcheck/daemon/src/system_report.py", line 601, in main
    runner.send_recurring_device_report()
  File "/home/pi/ttg-healthcheck/daemon/src/system_report.py", line 63, in send_recurring_device_report
    self.gen_report()
  File "/home/pi/ttg-healthcheck/daemon/src/system_report.py", line 32, in gen_report
    self.init_report()
  File "/home/pi/ttg-healthcheck/daemon/src/system_report.py", line 27, in init_report
    self.report.add_device_uuid()
  File "/home/pi/ttg-healthcheck/daemon/src/system_report.py", line 124, in add_device_uuid
    uuid=SysScrubber.fetch_device_uuid()
  File "/home/pi/ttg-healthcheck/daemon/src/system_report.py", line 209, in fetch_device_uuid
    uuid=re.findall(pattern, extract.read(), flags)[0]
IndexError: list index out of range
```

**Comment by Pyxsys** [comment]
The used linux command: `sudo dmidecode -s system-uuid` does not return any value when run on the reported environment.
```
pi@raspberrypi:~ $ cat /etc/*-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
pi@raspberrypi:~/ttg-healthcheck/daemon/linux/debian $ sudo dmidecode -s system-uuid
pi@raspberrypi:~/ttg-healthcheck/daemon/linux/debian $
```

**Comment by Pyxsys** [comment]
linux command `lsblk -o UUID` seems to be a useful alternative to dmidecode:
```
pi@raspberrypi:~/ttg-healthcheck/daemon $ lsblk -o UUID
UUID

10EB-30C5
223ecc81-7069-45f9-9309-c641eba776c8```

**Comment by Pyxsys** [comment]
Bug no longer occurs with commit 75c5d9cd053e6a920725d324327e40eb4955aaa6
