### ISSUE TITLE
[BUG] On deployed Pi, daemon fails to get network strength during recurring report generation

### ISSUE THREAD

**Issue by Pyxsys** [Pyxsys/ttg-healthcheck#217]
### **Describe the bug**
During recurring report flow, iw resource is busy by some other process, blocking the daemon from fetching the signal strength information. In the logs, the below is printed:
`command failed: Device or resource busy (-16)`

This cascades into an IndexError as the regex cannot find the expected expressions

### **To Reproduce**
1. Deploy the daemon on a PiOS x64 environment
2. Start the daemon using celebid -s
3. Wait 30s
4. Open the daemon log
5. See error

### **Expected behavior**
The command is executed by the daemon and the signal strength values are retrieved

### **Device (please complete the following information):**
 - type: Raspberry Pi
 - model: Raspberry Pi 3 Model B Plus Rev 1.3
 - OS: Debian GNU/Linux 11 (bullseye)
 - version: 11

### **Additional context**
Log output:
```txt

command failed: Device or resource busy (-16)
Starting new report routine at 2022-03-12 12:18:28.814591
        Writing report...
Traceback (most recent call last):
  File "/home/pi/ttg-healthcheck/daemon/src/system_report.py", line 608, in <module>
    main(sys.argv[1], sys.argv[2])
  File "/home/pi/ttg-healthcheck/daemon/src/system_report.py", line 601, in main
    runner.send_recurring_device_report()
  File "/home/pi/ttg-healthcheck/daemon/src/system_report.py", line 63, in send_recurring_device_report
    self.gen_report()
  File "/home/pi/ttg-healthcheck/daemon/src/system_report.py", line 35, in gen_report
    self.report.add_system_network_usage()
  File "/home/pi/ttg-healthcheck/daemon/src/system_report.py", line 116, in add_system_network_usage
    signal_strength = SysScrubber.fetch_network_strength()
  File "/home/pi/ttg-healthcheck/daemon/src/system_report.py", line 508, in fetch_network_strength
    str_as_num = re.findall(r"[-+]?(?:\d*\.\d+|\d+)", str_buffer[0])
IndexError: list index out of range
```

**Comment by Pyxsys** [comment]
Linux does not permit waiting for an individual resource. Solution is to retry and force weak connection if resource is consistently busy.
